name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  eslint-client:
    name: EsLint client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: EsLint
        run: yarn run eslint

  test-client:
    name: Test client
    runs-on: ubuntu-latest
    needs: eslint-client
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn

  build-client:
    name: Build client
    runs-on: ubuntu-latest
    needs: test-client
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extra metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/nuxt-client
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}